#!/bin/sh

cd $1

cd constant

ln -s ../../$2/constant solid

cd ../system

ln -s ../../$2/system solid

cd ../0

ln -s ../../$2/0 solid

cd ..

for d in processor*/; do
cd $d
cd 0
ln -s ../../../$2/$d/0 solid
cd ../constant
ln -s ../../../$2/$d/constant solid
cd ../..
done
